FROM nvidia/cuda:10.2-base-ubuntu18.04

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"

RUN apt-get -y update && apt-get install -y --no-install-recommends \
         wget \
         nginx \
         ca-certificates \
         python3-pip \
         python3 \
    && rm -rf /var/lib/apt/lists/* && \
    python3.6 -m pip install torch===1.4.0 torchvision===0.5.0 -f https://download.pytorch.org/whl/torch_stable.html && \
    python3.6 -m pip install numpy==1.16.2 scipy==1.2.1 scikit-learn==0.20.2 pandas flask gevent gunicorn && \
        (cd /usr/local/lib/python3.6/dist-packages/scipy/.libs; rm *; ln ../../numpy/.libs/* .) && \
        rm -rf /root/.cache

RUN python3.6 -m pip install transformers==2.6.0

#Install miniconda
#RUN wget \
#    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
#    && mkdir /root/.conda \
#    && bash Miniconda3-latest-Linux-x86_64.sh -b \
#    && rm -f Miniconda3-latest-Linux-x86_64.sh

COPY . /opt/program/

WORKDIR /opt/program
#RUN conda env create -f environment.yml
#RUN conda env create --name fake-news-classifier

#SHELL ["conda", "install", "-c", "conda-forge", "-n", "fake-news-classifier", "transformers"]

#SHELL ["conda", "run", "-n", "fake-news-classifier", "/bin/bash", "-c"]

COPY inference.py .
ENTRYPOINT ["python3.6", "inference.py"]